name: Build image

on:
  workflow_dispatch:  # allows manually triggered workflows
  push:
    branches:
      - main
      - master
    tags:
      - '*'

jobs:
  call-build:
    uses: haridusministeerium/workflows/.github/workflows/docker-build-publish.yml@master
    secrets: inherit
    with:
      image: layr/borg-mysql-backup

